#Configuraciones de spring
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: user
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: 'true'
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
#Configuracion del puerto del servidor
server:
  port: '8085'
#Configuraciones de schedule <<Cron>
cron:
  task: '*/10 * * * * *'